name: flutter_firebase_chat
description: Flutter Firebase Chat
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  flutter_bloc: ^8.1.3
  agora_rtc_engine: ^6.2.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.5
  photo_view: ^0.14.0
  timeago: ^3.6.0
  email_validator: ^2.1.17
  adaptive_action_sheet: ^2.0.2
  flutter_slidable: ^3.0.1
  visibility_detector: ^0.4.0+2
  keyboard_dismisser: ^3.0.0
  permission_handler: ^11.1.0
  http: ^1.2.1
  firebase_messaging: any
  flutter_callkit_incoming: ^2.0.4
  get: any
  record_mp3: ^3.0.0
  audioplayers: any
  bot_toast: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf